# The URL the site will be built for
base_url = "https://vaishnav-sabari-girish.codeberg.page/blog"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "zolanight"

generate_feeds = true

taxonomies = [
    { name = "tags" }
]

[markdown]

[markdown.highlighting]
theme = "Nord"

[extra]
# Put all your custom variables here

[extra.zolanight]
theme = "tokyonight"
home_list_latest_blog_posts = true
