name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

jobs:
  link-checker:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6

      - name: Check the links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --max-concurrency 1 -v --exclude "linkedin.com" content/*.md
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  spelling-checker:
    name: Check typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6

      - name: Run typos checker
        uses: crate-ci/typos@master
        with:
          files: content
